spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop